name: Lockfile update on package.json change

on:
  push:
    paths:
      - '**/package.json'   # trigger only when package.json changes
  workflow_dispatch:        # still useful for manual runs

permissions:
  contents: write           # required for committing changes
  pull-requests: write      # required for creating pull requests

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you have a .nvmrc file, you can use 'node-version-file' instead
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'      # or: node-version-file: '.nvmrc'

      - name: Update lockfile
        run: |
          npm i --package-lock-only --ignore-scripts
          git add package-lock.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(lockfile): update package-lock.json via CI"
          title: "chore(lockfile): update lockfile"
          body: |
            Automated update of `package-lock.json` after changes to `package.json`.
          branch: "ci/update-lockfile-${{ github.sha }}"
          delete-branch: true
          add-paths: |
            package-lock.json
          labels: |
            dependencies
            automated pr
